version: '3.8'

services:
  mysql:
    build:
      context: ./db/mysql/
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql/mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./db/mysql/mysql-confs/:/etc/mysql/conf.d/
      - mysql-storage:/var/lib/mysql
  sample-feed:
    build:
      context: ./sample_feed/
    container_name: sample-feed
    volumes:
      - ./sample_feed:/ltp/sample_feed
    ports:
      - "80:80"
    entrypoint:
      [ "/ltp/sample_feed/docker-entrypoint.sh" ]
    depends_on:
      - mysql
  celery-feed:
    build:
      context: ./sample_feed
      dockerfile: ./feed/celery.Dockerfile
    container_name: celery-feed
    volumes:
      - ./sample_feed:/ltp/sample_feed
    entrypoint:
      [ "/ltp/sample_feed/feed/docker-entrypoint-celery.sh" ]
    depends_on:
      - sample-feed
      - redis
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3005:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    user: root
  influxdb:
    image: influxdb:1.8.10-alpine
    platform: linux/amd64
    container_name: influx
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influx-storage:/var/lib/influxdb
  postgres:
    build:
      context: ./db/postgres/
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/postgres-init-files/:/docker-entrypoint-initdb.d/
      - ./db/postgres/postgres-conf/:/etc/postgresql/
      - postgres-storage:/var/lib/postgresql/data
  sample-chat:
    build:
      context: ./sample_chat/
    container_name: sample-chat
    volumes:
      - ./sample_chat:/ltp/sample_chat
    ports:
      - "8080:8080"
    entrypoint:
      [ "/ltp/sample_chat/docker-entrypoint.sh" ]
    depends_on:
      - postgres
  celery-chat:
    build:
      context: ./sample_chat
      dockerfile: ./src/chats/celery.Dockerfile
    container_name: celery-chat
    volumes:
      - ./sample_chat:/ltp/sample_chat
    entrypoint:
      [ "/ltp/sample_chat/docker-entrypoint-celery.sh" ]
    depends_on:
      - sample-chat
      - redis
    tty: true
    stdin_open: true
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  id-generator:
    build:
      context: ./id_generator/
    container_name: id-generator
    volumes:
      - ./id_generator:/ltp/id_generator
    ports:
      - "50051:50051"
    entrypoint:
      [ "/ltp/id_generator/docker-entrypoint.sh" ]
volumes:
  grafana-storage: {}
  influx-storage: {}
  mysql-storage: {}
  postgres-storage: {}
