version: '3.8'

services:
  sample-feed:
    build:
      context: ./sample_feed/
    container_name: sample-feed
    volumes:
      - ./sample_feed:/ltp/sample_feed
    ports:
      - "80:80"
    entrypoint:
      [ "/ltp/sample_feed/docker-entrypoint.sh" ]
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    depends_on:
      - mysql
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3005:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    user: root
  influxdb:
    image: influxdb:1.8.10-alpine
    platform: linux/amd64
    container_name: influx
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    tty: true
    stdin_open: true
    volumes:
      - influx-storage:/var/lib/influxdb
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: sample-feed
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/mysql-init-files/:/docker-entrypoint-initdb.d/
      - mysql-storage:/var/lib/mysql
volumes:
  grafana-storage: {}
  influx-storage: {}
  mysql-storage: {}
