"""fix field names

Revision ID: 218540898d6b
Revises: 9fcb39f31c80
Create Date: 2023-12-30 07:46:46.414917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '218540898d6b'
down_revision: Union[str, None] = '9fcb39f31c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('shortId', sa.CHAR(length=6), nullable=True))
    op.add_column('short_url', sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index('ix_short_url_short_id', table_name='short_url')
    op.create_index(op.f('ix_short_url_shortId'), 'short_url', ['shortId'], unique=True)
    op.drop_column('short_url', 'short_id')
    op.drop_column('short_url', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('short_url', sa.Column('short_id', mysql.CHAR(length=6), nullable=True))
    op.drop_index(op.f('ix_short_url_shortId'), table_name='short_url')
    op.create_index('ix_short_url_short_id', 'short_url', ['short_id'], unique=True)
    op.drop_column('short_url', 'createdAt')
    op.drop_column('short_url', 'shortId')
    # ### end Alembic commands ###
